declare A
	x : Integer
	y : Integer
end

rule "Initializing Working Memory..."
	then
		System.out.println(drools.getRule().getName());
		insert(new A(0, 0));
end

rule "Self-Activating Rule"
	when
		$a : A(x == 0)
	then
		System.out.print(drools.getRule().getName());
		System.out.print(": ");
		System.out.print($a);
		modify($a) {
			setY(1)
		}
		System.out.print(" > ");
		System.out.println($a);
end
